#ifndef QTCHROMECAST_GLOBAL_H
#define QTCHROMECAST_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTCHROMECAST_LIBRARY)
#  define QTCHROMECASTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTCHROMECASTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCHROMECAST_GLOBAL_H
